### ISSUE TITLE
Design: I am not sure the current design (the wall switches to white when correct answer) makes it sufficiently clear that the user can go through the wall.

### ISSUE THREAD

**Issue by jeanbaptistedeborman** [jeanbaptistedeborman/pacman#22]
I would propose to switch to apply transparency (about 70%)

**Comment by Nostok** [comment]
Email discussion with GK.

GK: Can the avatar move in front of it?
JB: Yes, of course but this is a separate issue (see bug #28: the player/badguys are hidden behind the wall ...). This bug will be fixed ASAP.
GK: Also, would a transparency level help?
JB: I am quite sure about it (This is the way the previous game worked :  by fading the blocks into the background). If you wish, I can easily add some transparency  so you can test it.
GK: OK

**Comment by jeanbaptistedeborman** [comment]
Seems accepted by client
